### ISSUE TITLE
Unable to parse XML returned by server

### ISSUE THREAD

**Issue by AymenHARRATH** [superfell/zkSforce#20]
I am using the latest version of zkSforce for querying Salesforce (32.0).
After being logged in using this method: 

    -(ZKLoginResult *)login:(NSString *)un password:(NSString *)pwd;

I sometimes (randomly, specially when connection is low) get the following exception thrown in zkBaseClient.m file:

    @throw [NSException exceptionWithName:@"Xml error" reason:@"Unable to parse XML returned by server" userInfo:nil]

while querying Salesforce using this method: 

    -(ZKQueryResult *)query:(NSString *)queryString;

I am not able to catch the exception and my application crashes in the specified file (zkBaseClient.m).

Here is the part of code responsible for executing the query to Salesforce.  

    if (![[[ZKSforceClientManager sharedSFClient] salesForceClient] loggedIn])
            {
                [[[ZKSforceClientManager sharedSFClient] salesForceClient] login:USERNAME   password:PASSWORD];
            }
    ZKQueryResult *qr = [[[ZKSforceClientManager sharedSFClient] salesForceClient] query:[NSString stringWithFormat:@"SELECT Name , id , IsActive , Status, ParentId  FROM Campaign WHERE Name LIKE %@ ",@"Some dynamic String"]];

ZKSforceClientManager is a singleton class holding an instance of ZKSforceClient
Here is the code :

    @interface ZKSforceClientManager : NSObject{
        ZKSforceClient *salesForceClient;

    }
    @property (nonatomic, retain) ZKSforceClient *salesForceClient;

    + (ZKSforceClientManager *)sharedSFClient;
    @end

    @implementation ZKSforceClientManager

    @synthesize salesForceClient;

    + (ZKSforceClientManager *)sharedSFClient{
    
        static ZKSforceClientManager *sharedSFClient = nil;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            sharedSFClient = [[self alloc] init];
        });
        return sharedSFClient;
    }

    - (id)init {
        if (self = [super init]) {
            salesForceClient = [[ZKSforceClient alloc] init];
        }
        return self;
    }

    @end

The crash is not produced regularly; it is often when Internet connection is low.

Can you please help me solving this problem??

Thank you,

**Comment by superfell** [comment]
What OS is this on?
when you say you can't catch the exception, what do you mean?
@try / @catch should handle it fine (see SoqlX for an example usage)
the client object is not thread safe, you have a single object, what are you doing to ensure its only use by one thread at a time? are all calls on the UI thread?

**Comment by AymenHARRATH** [comment]
I am using iOS 7.1.2.

All my calls are on the main thread and all of them are made synchronously.
I couldn't handle the crash with @try / @catch because it is in the zkBaseClient.m class.

I want to point out the fact that this crash is randomly produced.

**Comment by superfell** [comment]
The exception will go up the call stack until its caught, you can catch it
from your code
