### ISSUE TITLE
Review TLS support

### ISSUE THREAD

**Issue by superfell** [superfell/zkSforce#22]
Starting 2016 Salesforce is disabling TLS 1.0 support, review its potential impact
https://help.salesforce.com/HTViewSolution?id=000221207&language=en_US

**Comment by cramoisan** [comment]
Hi Simon, any update on this ?

**Comment by superfell** [comment]
Not yet.

**Comment by superfell** [comment]
As far as i can tell TLS 1.2 support is provided on all recent OS versions (both iOS & OSX). This shouldn't be an issue. using ZKSforce on OSX 10.9 i was able to communicate with a server that had TLS 1.0 turned off and everything worked fine.
