### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by zav333** [superfell/zkSforce#23]
Hello Simon,

How I can authentication with zkBaseClient using Single Sign-On?

http://resources.docs.salesforce.com/198/0/en-us/sfdc/pdf/salesforce_single_sign_on.pdf

Thank you

**Comment by superfell** [comment]
zkSforce supports the OAuth flows (which can do SSO), that's a big doc, can you point to something specific?

**Comment by zav333** [comment]
Thank you. You really helped
