### ISSUE TITLE
Downloading attachments block ui interaction.

### ISSUE THREAD

**Issue by asif13** [superfell/zkSforce#35]
In zkBaseClient.m, there is a synchronous call made in method sendRequest at line 89, which is blocking the UI till the request is completed.Is there any workaround to not have the UI blocked ?
The code in question is :
`    NSData *respPayload = [NSURLConnection sendSynchronousRequest:request returningResponse:&resp error:&err];`

**Comment by superfell** [comment]
Use any of the blocks versions of the calls for it to not block the main
thread

**Comment by superfell** [comment]
There's a note about this and an example in the readme
