### ISSUE TITLE
Cannot build 'query-OSX'

### ISSUE THREAD

**Issue by SteveDCronin** [superfell/zkSforce#44]
I see 4  file not found issues: 
'/Users/steve/Documents/GitHub/zkSforce/zkSforce/zkSforceClient+zkAsyncQuery.m'
'/Users/steve/Documents/GitHub/zkSforce/zkSforce/zkSforceClient+Operations.m'
'/Users/steve/Documents/GitHub/zkSforce/zkSforce/zkDescribeSObject.m'
'/Users/steve/Documents/GitHub/zkSforce/zkSforce/zkDescribeGlobalSObject.m'

These errors arise because in $(SRCROOT)/zkSforce/ these files exist as:
ZKSforceClient+zkAsyncQuery.m
ZKSforceClient+Operations.m
ZKDescribeSObject.m
ZKDescribeGlobalSObject.m

NOTE the capitalization difference...

Please advise as to the best way to rectify this matter.

**Comment by superfell** [comment]
What OS & Xcode version are you using? I did a fresh checkout and it built fine with Xcode 10.2.1 on OSX 10.14.5, with the code on an APFS volume.

**Comment by SteveDCronin** [comment]
Using the same tools...
I fiddled around in Xcode (refunding files..) and now works...  Bleh - sorry for the trouble.
I'm going to close but I don't really understand what happened...

Thanks for quick response!
