### ISSUE TITLE
Clarify comment in OAuthDemo re refresh_token?

### ISSUE THREAD

**Issue by SteveDCronin** [superfell/zkSforce#45]
In 
`- (void)getUrl:(NSAppleEventDescriptor *)event withReplyEvent:(NSAppleEventDescriptor *)replyEvent

NSString *url = [event paramDescriptorForKeyword:keyDirectObject].stringValue;    
ZKSforceClient *client = [[ZKSforceClient alloc] init];

[client loginFromOAuthCallbackUrl:url oAuthConsumerKey:OAUTH_CLIENTID];

// in a real app, you'd save the refresh_token & auth host to the keychain, and on
    // relaunch, try and intialize your client from that first, so that you can skip
    // the login step.`

I have all this working but was shocked that
`	ZKOAuthInfo *oauth = (ZKOAuthInfo *)client.authenticationInfo;

NSString *refreshToken = oauth.refreshToken;
`

refreshToken is nil upon the execution of this method...  
Therefore this token cannot be stored in the keychain within this method....

When will the refreshToken exist such that I can actually store this token?
Perhaps adding some clarifying comments in the method would help..

Interestingly (at least to me) the 'url' above DOES contain an 'access_token'...
I don't see a direct 'zk' way to obtain this token...
Is this token useful to me?
e.g.: 
url:xyz.abc.productName-salesforce:/oauth#access_token=00D3i000000EL1H%21ARIAQBFx43ZxdTW2Q8NYcWxXsPmY_Bsi9OQQSd4s2CWCFV9t7aeVKTlrQVdSgybd1wT9TgLx9F_K8bJYTdaSjD1zIrJvR3Ld&instance_url=https%3A%2F%2Fna112.salesforce.com&id=https%3A%2F%2Flogin.salesforce.com%2Fid%2F00D3i000000EL1HEAW%2F0053i000000uchMAAQ&issued_at=1563145801852&signature=XonWtMrqpGGeL3ejD%2FYifw7F5aHiiTbcCCzqjirC784%3D&scope=api&token_type=Bearer

Thanks for such a nice tool!

**Comment by SteveDCronin** [comment]
If, instead of saving the refresh_token and auth host, I save the url from above and then later (after a relaunch) simply do:
[client loginFromOAuthCallbackUrl:url oAuthConsumerKey:OAUTH_CLIENTID];

will this work?

**Comment by superfell** [comment]
In order to get a refresh token, your oauth consumer config needs to include the scope "Perform requests on your behalf at any time". Once you update the config, then you should get the refresh token that you can then stash away. As you've seen regular session Ids (aka access tokens) expire

**Comment by SteveDCronin** [comment]
Bingo!  
This seems like advice that should be made directly visible to any to new users!  

Thank-You.

**Comment by SteveDCronin** [comment]
What is your recommendation for the Refresh Token Policy?

In the meantime I’ve set it to ‘valid until revoked’…

**Comment by superfell** [comment]
reopening to remind me to update the comments.

Valid until revoked seems reasonable, that's how most oauth flows work.
