### ISSUE TITLE
Clue to more robust data handling

### ISSUE THREAD

**Issue by SteveDCronin** [superfell/zkSforce#46]
You have posted an example usage which begins like this:
    ZKSObject *contact = [ZKSObject withType:@"Contact"];
    [contact setFieldValue:@"Fell" field:@"LastName"];
    [contact setFieldValue:@"Simon" field:@"FirstName"];
...

After reviewing the SOAP API I add:
  [contact setFieldValue:@"US" field:@"MailingCountryCode"];

I receive this error:
INVALID_FIELD: No such column 'MailingCountryCode' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.

I do see that the API specifies that 'MailingCountryCode' is a picklist value.  
But I don't have any clues as to how I use the 'ZK' tools to assign a picklist value.
I'm under the impression that it is pretty easy once you get 'it'!
Can you help me out here and elaborate on how I might assign a picklist value?

**Comment by superfell** [comment]
From the API POV there’s nothing particularly interesting about pick lists, what you have should work. The error message says you don’t have access to the field, you’d need to check the salesforce config for that. Tools like SoqlX can help you explore what is available in the API
