### ISSUE TITLE
Any Plans to Update 2 Deprecated iOS calls?

### ISSUE THREAD

**Issue by SteveDCronin** [superfell/zkSforce#48]
Simon;

Thanks for this very useful code!  I'm using it for both macOS and now building for iOS.

Since you recently made an update, I wonder if you have any plans to update the 2 iOS calls which use 'NSURLConnection sendSynchronousRequest..'?

zkBaseClient:
- (zkElement *)sendRequest:(NSString *)payload name:(NSString *)callName returnRoot:(BOOL)returnRoot;

zKAuthentication:
-(void)refresh;

This NSURLConnection method was first deprecated in iOS 9...
These are the only 2 issues that the Xcode 10.3 compiler flags!
Thanks Again.
Steve

**Comment by superfell** [comment]
I haven't had time to look into that, and I'm not likely to anytime soon. I'd welcome some help/PRs in that area.

**Comment by superfell** [comment]
See #39 as well.

**Comment by superfell** [comment]
This would probably mean deprecating or removing the synchronous versions of the calls into the client object.

**Comment by SteveDCronin** [comment]
while not knowing enuf of the internals to make cogent comments….

is there a problem with going fully asynchronous?

**Comment by superfell** [comment]
No specific problem that I'm aware of. The client object already exposes an async blocks based version of most calls. It's going to be a lot of internals shuffling to make the sync version built on top of the async versions, instead of the other way around. At least most of that code is code gen'd.

**Comment by superfell** [comment]
There's more stuff to do, but i put my progress so far up on the urlSession_2 branch if you want to check it out.

**Comment by SteveDCronin** [comment]
On Sep 7, 2019, at 1:18 PM, Simon Fell <notifications@github.com> wrote:
> There's more stuff to do, but i put my progress so far up on the urlSession_2 branch if you want to check it out.
> 
> 

Simon;

This is great news!   Thank-you for your effort on this!

I'm using CocoaPods from managing the various dependencies.
As of now I am using:  
…
pod ‘ZKSforce’, ‘~> 46.0.0’

How would I adapt that statement to utilize what you just uploaded?

Steve

**Comment by superfell** [comment]
It looks like you can change your pod reference to point to local code. see "Using files from a local path" section at https://guides.cocoapods.org/syntax/podfile.html#pod

So you should be able to clone this repo, checkout the urlSession_2 branch, and then update the pod to point to that copy instead.

**Comment by SteveDCronin** [comment]
On Sep 7, 2019, at 3:06 PM, Simon Fell <notifications@github.com> wrote:
> It looks like you can change your pod reference to point to local code. see "Using files from a local path" section at https://guides.cocoapods.org/syntax/podfile.html#pod <https://guides.cocoapods.org/syntax/podfile.html#pod>
> So you should be able to clone this repo, checkout the urlSession_2 branch, and then update the pod to point to that copy instead.
> 

Simon;

Thanks for the detailed and quick response!  I'll let you know of any issues.

Steve

**Comment by SteveDCronin** [comment]
|| So you should be able to clone this repo, checkout the urlSession_2 branch, and then update the pod to point to that copy instead.



So the pod now looks like:
…
pod ‘ZKSforce’, :path => ‘~/Douments/Github/zkSforce2'
...

When I run a new ‘pod install’ I get the error:  no podspec found

There is a ‘ZKSforce.podspec.json’ file but it is JSON format - not formatted like other podspec files…

Is there a tool to transform podspec.JSON?

**Comment by superfell** [comment]
Unless it changed in the last few months, the json format is supported.  I don't know cocoa pods very well, just enough to keep publishing the pod spec for this project. The docs do say you can point to a branch, didn't see that before, so you might be able to use that instead.

pod 'ZKSforce', :git => 'https://github.com/superfell/zkSforce.git', :branch => 'urlSession_2'

**Comment by superfell** [comment]
The more i look at it, the more i want to just remove all the sync code, clean up some other stuff and declare that the next major version will have a breaking API change.

**Comment by SteveDCronin** [comment]
On Sep 7, 2019, at 4:45 PM, Simon Fell <notifications@github.com> wrote:
> pod 'ZKSforce', :git => 'https://github.com/superfell/zkSforce.git <https://github.com/superfell/zkSforce.git>', :branch => 'urlSession_2’
> 
That got me over the hump - verified that updated code placed into the Pods 
So now am ready to make use of the branch!

Thanks Again for your efforts, your patience, and your responsiveness!

Steve

**Comment by SteveDCronin** [comment]
On Sep 7, 2019, at 5:07 PM, Simon Fell <notifications@github.com> wrote:

> The more i look at it, the more i want to just remove all the sync code, clean up some other stuff and declare that the next major version will have a breaking API change.

Consider this one vote in favor of this plan….  

Async is the modern way - those who aren’t willing to renovate can just stay put on 46..  

Do what is right for the product long term

**Comment by superfell** [comment]
I turned the shadow warning on, it may of been default off in Xcode when the projects were initially created (which was a long time ago). I don't see the ZKSforce_Prefix.pch file is this repo, is it an artifact of how cocoa pods work?

**Comment by SteveDCronin** [comment]
The file I am referring to is known as a 'Prefix Header'. If you look at your sample projects in 'urlSession_3’ you will find they each have such a '.pch' file.  You will see this set in the build settings for each of these projects...

What I would suggest you do is start a brand new Xcode project (ideally 2 - a macOS & an iOS app)
Open a new 'Pod' file for this new project and include the following in that 'Pod' file:
 pod 'ZKSforce', :git => 'https://github.com/superfell/zkSforce.git <https://github.com/superfell/zkSforce.git>', :branch => 'urlSession_3’
Do a 'pod install' and then examine the compilation results in this new project

Your samples don't use CocoaPods to build out their ZKSforce capability -  but your users do!!

What I believe you will notice is the effect of the .pch mentioned above as well as the ill effects of simply copying the prodspec file from the master branch without any further tag assignment...

FWIW:  I have a macOS project using 'urlsession_3' there are only 2 warnings at this point:
.../ZKSforce/ZKBaseClient.m:63:13: Weak property 'delegate' is accessed multiple times in this block but may be unpredictably set to nil; assign to a strong variable to keep the object alive

.../ZKSforce/ZKAuthentication.m:239:32: Weak property 'userInfo' is accessed multiple times in this block but may be unpredictably set to nil; assign to a strong variable to keep the object alive

Turning now to iOS...

**Comment by superfell** [comment]
I pushed a few more fixes and an update to the pod spec. I see cocoa pods creates the zksforce-prefix.pch file, but it only appears to be used for the pod build, not for the project that depends on the pod. Does the new pod spec solve your issue?

**Comment by SteveDCronin** [comment]
Spot on!
The updated podspec solves my build issue beautifully.

Thank-you for all the recent hard work!!

**Comment by superfell** [comment]
Great!. There's a couple of things left to sort out, and then I'll merge this to master with the upcoming  salesforce v47 API changes.

**Comment by SteveDCronin** [comment]
Hey maybe not necessary or useful but..

I've implemented the asynchronous calls in both macOS & iOS clients and they are working dandy...

Mind you this in no way a systemic validation but my usage of ZKSforce urSession_3 is working great!

**Comment by superfell** [comment]
Glad to hear its working out for you. I made a few final tweaks/bug fixes and have also included the changes from the just released V47. I'll be updating cocoa pods shortly. Thanks for your input on this one. BTW, I'd be interested to hear about what you're using ZKSforce for, if you're able to say.
