### ISSUE TITLE
Missing Method?

### ISSUE THREAD

**Issue by SteveDCronin** [superfell/zkSforce#53]
In the read.me it is stated: "...All the callback block run on the main thread/queue. If you'd like the callbacks to run on a specific queue, there's version of each API call that takes an additional queue parameter to set the callback queue..."

Later in the readme you show this example:
`[sforce loginWithRefreshToken:refreshToken authUrl:authHost oAuthConsumerKey:OAUTH_CLIENTID
		failBlock:^(NSError *err) {
			[[NSAlert alertWithError:err] runModal];
		}
        completeBlock:^{
			NSLog(@"Successfully initialized from refresh token");
}];
`

When I attempt to use this I get this error:
No visible @interface for 'ZKSforceClient' declares the selector 'loginWithRefreshToken:authUrl:oAuthConsumerKey:failBlock:completeBlock:'

NOTE: There is a method which has a queue parameter before the failBlock!

**Comment by superfell** [comment]
Thanks, yes, does look like some of the calls that aren't code generated aren't consistent. I'll add the missing versions in.
